"""Named MCP server over stdio and streamable HTTP (Phase 4, ADR-0014).

Every tool is generated by iterating :data:`~groundkit.service.tools.TOOLS`.
Nothing here hand-registers an operation, and that is ADR-0014 decision 2
check 3: an MCP-only tool is caught exactly as a REST-only route is, because
:func:`list_tool_definitions` drives the server's *registered* handler and
``tests/test_service_mcp.py`` compares what comes back against ``TOOL_NAMES``.
Each tool's ``inputSchema`` is ``request_model.model_json_schema()`` — a
hand-written second schema and a Pydantic model are two descriptions of one
contract, which is precisely the seam drift ADR-0001 hazard 4 exists to catch
(ADR-0014 decision 5).

## The dispatch body catches everything, and that is a disclosure control

The SDK's generated ``tools/call`` handler ends in::

    except Exception as e:
        return self._make_error_result(str(e))

and ``_make_error_result`` puts that raw string into the ``CallToolResult`` a
client reads. An escaping exception therefore *returns its own message to the
caller*, bypassing ADR-0014 decision 9's allow-list entirely — a
:class:`~groundkit.errors.StorageError` carries an absolute database path and an
:class:`~groundkit.errors.EmbeddingError` may carry a provider endpoint or
response text. So the handler registered below catches
:class:`~groundkit.errors.GroundkitError` **and** bare ``Exception`` itself and
returns an explicit :class:`mcp.types.CallToolResult` built from
:mod:`groundkit.service.errors`. The SDK's stringify branch is unreachable by
construction rather than unlikely in practice, and ``test_service_mcp.py``
proves it with a sentinel planted in both a message and a ``__cause__``.

``CancelledError`` is deliberately *not* caught: it is a ``BaseException`` in
3.11+, so ``except Exception`` lets a cancelled request unwind rather than
answering it with a fabricated error result.

Serialization runs inside that same guard, for the same reason. Returning a
plain ``dict`` and letting the SDK render it would move ``json.dumps`` back
inside the SDK's ``try``, restoring the stringify path for anything unserializable.

## Input validation is ours, not the SDK's

``validate_input=False``. With the SDK's own jsonschema check enabled, a bad
argument returns ``f"Input validation error: {e.message}"`` — a bare string with
no ``kind`` and no ``code``, produced by a code path neither transport controls.
That would make MCP and REST disagree about how a malformed request is rendered,
which ADR-0014 decision 5 lists under *must not differ*. Parsing through
``spec.request_model`` instead means one validator (the model), one renderer
(:mod:`groundkit.service.errors`), and the same answer on both surfaces.

## stdout carries JSON-RPC frames and nothing else

ADR-0014 decision 5's stdio rule is load-bearing: a single log line on stdout
corrupts the protocol stream. :func:`run_stdio` therefore re-points every
stdout-bound stream handler at stderr *before* the server runs, and a test
captures stdout across a real tool call and asserts every line parses as JSON.
A stray ``print()`` in a handler is still fatal and cannot be defended against
from here; nothing in :mod:`groundkit.service` prints.
"""

from __future__ import annotations

import json
import logging
import sys
import time
from typing import TYPE_CHECKING, Any, Final
from uuid import uuid4

import mcp.types as types
from mcp.server.lowlevel import Server
from mcp.server.stdio import stdio_server
from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
from mcp.server.transport_security import TransportSecuritySettings
from pydantic import BaseModel, ValidationError

from groundkit import __version__
from groundkit.errors import ConfigurationError, GroundkitError
from groundkit.service.binding import LOOPBACK_HOST_ALLOW_LIST, HostAllowList
from groundkit.service.errors import (
    check_collection,
    map_exception,
    unexpected_error_rendering,
)
from groundkit.service.tools import TOOLS, result_count

if TYPE_CHECKING:
    from groundkit.service.errors import ErrorRendering
    from groundkit.service.tools import ServiceContext, ToolResult, ToolSpec

logger = logging.getLogger(__name__)

#: Server name reported in ``initialize``. Stable, because clients key their
#: stored configuration on it.
MCP_SERVER_NAME: Final[str] = "groundkit"

#: Path the streamable-HTTP transport is mounted on. Exported rather than
#: written into ``cli.py``, so the mount point and the documented client
#: configuration cannot drift apart.
MCP_HTTP_PATH: Final[str] = "/mcp"

#: Key wrapping ``list_collections``'s result. MCP's ``structuredContent`` is a
#: JSON **object** — the protocol has no array form — so a bare ``list[str]``
#: cannot be carried there at all. Wrapping keeps the result machine-readable
#: instead of degrading it to a JSON string in a text block. This is framing,
#: which ADR-0014 decision 5 lists as *differs deliberately* between transports;
#: the operation, its request model and its error codes are what must not differ.
LIST_COLLECTIONS_RESULT_KEY: Final[str] = "collections"

#: Cap on how many validation problems one rejection reports. A request that is
#: wrong in twenty ways does not need twenty lines to be actionable, and an
#: unbounded list is caller-controlled response size.
_MAX_REPORTED_VALIDATION_ERRORS: Final[int] = 5

#: Idle sessions are reaped rather than accumulating for the process lifetime.
#: The service has no authentication (ADR-0014 decision 1), so an unbounded
#: session map is memory any caller reaching the port can allocate; the loopback
#: bind bounds who that is, not how much. Matches the SDK's own recommendation.
_SESSION_IDLE_TIMEOUT_SECONDS: Final[float] = 1800.0

#: Sent to clients at ``initialize``. States the read-only contract up front so
#: an agent does not go looking for an ingest tool that is deliberately absent
#: (SPEC.md §1.2).
_INSTRUCTIONS: Final[str] = (
    "groundkit serves citation-verifiable retrieval over locally ingested collections. "
    "Every tool is read-only: nothing here ingests, updates, or deletes — collections are "
    "created by the `grk ingest` CLI. Call list_collections to learn what exists, search one "
    "of them, then fetch_chunk a hit you intend to quote: it re-reads the cited span from the "
    "source file and reports whether the citation still holds."
)


def _tool_definition(spec: ToolSpec) -> types.Tool:
    """Render one registry entry as an MCP tool.

    ``inputSchema`` is *generated* from the request model. A second,
    hand-written schema is the ADR-0001 hazard 4 drift — two descriptions of one
    contract, with nothing forcing them to agree — and ADR-0014 decision 5
    forbids it in these words.

    ``readOnlyHint`` is derived from ``side_effect`` rather than hardcoded
    ``True``, so widening ``SideEffect`` can never leave a mutating tool
    advertising itself as a read. ``openWorldHint`` is ``False`` because every
    operation is bounded by this server's index directory; the hints the MCP
    spec defines as meaningful only when ``readOnlyHint`` is false are left
    unset rather than asserted.
    """
    return types.Tool(
        name=spec.name,
        description=spec.summary,
        inputSchema=spec.request_model.model_json_schema(),
        annotations=types.ToolAnnotations(
            readOnlyHint=spec.side_effect == "read_only",
            openWorldHint=False,
        ),
    )


def _error_result(rendering: ErrorRendering, request_id: str) -> types.CallToolResult:
    """Build the one error shape this transport returns.

    Carries ``kind`` and ``code`` so a client branches on a stable token rather
    than parsing ``detail`` — the failure mode prose invites — and ``request_id``
    so an operator can join the caller's report to the server-side log record
    holding the full, unscrubbed exception. ``status_code`` is deliberately
    absent: HTTP framing belongs to the REST transport.

    The payload is duplicated into ``content`` as text because a client that
    reads only content blocks must still see the failure; both halves are built
    from the same dict, so they cannot disagree.
    """
    payload: dict[str, Any] = {
        "detail": rendering.detail,
        "kind": rendering.kind,
        "code": rendering.rpc_code,
        "request_id": request_id,
    }
    return types.CallToolResult(
        content=[types.TextContent(type="text", text=json.dumps(payload, indent=2))],
        structuredContent=payload,
        isError=True,
    )


def _success_result(result: ToolResult) -> types.CallToolResult:
    """Render a handler's return value, JSON-safe.

    ``model_dump(mode="json")`` rather than ``model_dump()``: the latter leaves
    non-JSON scalars in place, which would fail at serialization time — inside
    the SDK's ``except Exception`` if we returned a raw dict and let it render.
    Dumping here keeps that path unreachable.
    """
    structured: dict[str, Any]
    if isinstance(result, BaseModel):
        structured = result.model_dump(mode="json")
    else:
        structured = {LIST_COLLECTIONS_RESULT_KEY: list(result)}
    return types.CallToolResult(
        content=[types.TextContent(type="text", text=json.dumps(structured, indent=2))],
        structuredContent=structured,
        isError=False,
    )


def _validation_detail(exc: ValidationError) -> str:
    """Summarize a rejected request without echoing what was submitted.

    Reports each problem's ``loc`` and ``type`` only — never ``msg`` and never
    ``input``. ``type`` is a stable machine token (``string_too_long``,
    ``extra_forbidden``) a client can branch on, while ``input`` is the caller's
    own value and has no business being reflected back through a server that
    also logs it.
    """
    problems = [
        f"{'.'.join(str(part) for part in error['loc']) or '(root)'}: {error['type']}"
        for error in exc.errors()[:_MAX_REPORTED_VALIDATION_ERRORS]
    ]
    return f"invalid arguments for this tool: {'; '.join(problems)}"


def _spec_for(name: str) -> ToolSpec:
    """Look a tool up in the registry, or refuse.

    Scans :data:`TOOLS` rather than consulting a module-level index built from
    it: a derived mapping is a second copy of the registry, and the registry is
    four entries. Reading it at dispatch time is also what makes the
    injected-violation test in ``test_service_mcp.py`` exercise the real path.

    The unknown name is *not* echoed into the detail — it is unvalidated
    caller-supplied text, and a client that guessed wrong learns the true tool
    set from ``tools/list``. It is recorded server-side instead.

    Raises:
        ConfigurationError: No registered tool carries this name.
    """
    for spec in TOOLS:
        if spec.name == name:
            return spec
    raise ConfigurationError(
        "unknown tool; this server exposes exactly the tools returned by tools/list"
    )


def _parse_request(spec: ToolSpec, arguments: dict[str, Any]) -> BaseModel:
    """Parse ``arguments`` into the tool's declared request model.

    The ``ValidationError`` is chained as ``__cause__`` so the server-side log
    keeps the full detail, and that is safe *because* the mapper never reads a
    cause — the ADR-0001 hazard 6 discipline is what makes chaining here a
    diagnostic rather than a leak.

    Raises:
        ConfigurationError: The arguments do not satisfy the model. Maps to
            ``invalid_request`` through the shared renderer, so MCP and REST
            answer a malformed request identically.
    """
    try:
        return spec.request_model.model_validate(arguments)
    except ValidationError as exc:
        # `from None`, deliberately, and this is the one place in this module
        # where dropping a cause is the correct call rather than a lossy one.
        # `_validation_detail` reports `loc` and `type` only, precisely because
        # (its own words) `input` "has no business being reflected back through
        # a server that also logs it" — but `from exc` handed the raw
        # `ValidationError` to `__cause__`, and `_call_tool`'s
        # `logger.error(..., exc_info=exc)` renders the whole chain. So the
        # client response was sanitized while the SERVER LOG carried the
        # rejected input verbatim, which is the leak the sanitizing existed to
        # prevent, moved one channel over. CLAUDE.md requires scrubbing to cover
        # `__cause__` chains, not just messages. The `loc`/`type` summary is
        # what an operator needs; the submitted value is what they must not get.
        raise ConfigurationError(_validation_detail(exc)) from None


async def _dispatch(
    ctx: ServiceContext, name: str, arguments: dict[str, Any], request_id: str
) -> types.CallToolResult:
    """Resolve, validate, and run one tool call.

    Raises rather than rendering its own failures: the registered handler owns
    the single conversion point, so every error leaves this transport through
    exactly one function.

    The collection precondition (ADR-0014 decision 3) runs **before** any
    handler, and it is found via ``getattr`` rather than a per-tool table. The
    presence of a ``collection`` field is the request model's own declaration,
    so a tool added later is covered without anyone remembering to update a list
    here — a list that would fail open when they forgot.
    """
    spec = _spec_for(name)
    request = _parse_request(spec, arguments)

    collection = getattr(request, "collection", None)
    if isinstance(collection, str):
        rendering = check_collection(ctx.index_dir, collection)
        if rendering is not None:
            logger.info(
                "mcp tool=%s request_id=%s refused kind=%s",
                name,
                request_id,
                rendering.kind,
                extra={"tool": name, "request_id": request_id, "failure_kind": rendering.kind},
            )
            return _error_result(rendering, request_id)

    started = time.perf_counter()
    result = await spec.handler(ctx, request)
    latency_ms = (time.perf_counter() - started) * 1000.0
    # For a successful MCP call this line is the ONLY access record — there is
    # no equivalent of the REST surface's separate access log — so it owes the
    # same fields SPEC.md §3 names: request id, latency, result count, and (on
    # the failure paths below) the typed failure code. `result_count` is
    # imported from `service/tools.py` rather than reimplemented here so the
    # two transports cannot drift into disagreeing about what a result is.
    # Neither the query nor any retrieved content appears: same rule as the
    # REST access line (ADR-0014 decision 9).
    logger.info(
        "mcp tool=%s request_id=%s ok latency_ms=%.2f results=%d",
        name,
        request_id,
        latency_ms,
        result_count(result),
        extra={
            "tool": name,
            "request_id": request_id,
            "status": "ok",
            "latency_ms": latency_ms,
            "results": result_count(result),
        },
    )
    return _success_result(result)


def build_mcp_server(ctx: ServiceContext) -> Server[Any, Any]:
    """Build the MCP server for ``ctx``, with one tool per registry entry.

    ``ctx`` is captured once, at build time. That is ADR-0014 decision 6 in
    mechanical form: provider settings, the index directory and the containment
    root reach a handler only through this object, so no request model needs to
    carry them and no request can reach them.

    Args:
        ctx: Serve-time context every handler is invoked with.

    Returns:
        A server with ``tools/list`` and ``tools/call`` registered.
    """
    server: Server[Any, Any] = Server(
        name=MCP_SERVER_NAME,
        version=__version__,
        instructions=_INSTRUCTIONS,
    )

    async def _list_tools() -> list[types.Tool]:
        return [_tool_definition(spec) for spec in TOOLS]

    async def _call_tool(name: str, arguments: dict[str, Any]) -> types.CallToolResult:
        """Answer one ``tools/call``, and never let an exception escape.

        Both ``except`` clauses are load-bearing, not defensive style: an escape
        reaches the SDK's ``return self._make_error_result(str(e))``, which puts
        the raw message in front of the caller. See this module's docstring.
        """
        request_id = uuid4().hex
        try:
            return await _dispatch(ctx, name, arguments, request_id)
        except GroundkitError as exc:
            # Mapped BEFORE logging, not inline in the return below, so the log
            # record carries the same typed `kind` the caller receives. Without
            # it a collector sees only status="failed" and cannot tell a
            # storage fault from a retrieval one from an index inconsistency —
            # the precondition-refusal path above already logs `failure_kind`,
            # and this being the odd one out was the inconsistency.
            rendering = map_exception(exc)
            logger.error(
                "mcp tool=%s request_id=%s failed kind=%s",
                name,
                request_id,
                rendering.kind,
                exc_info=exc,
                extra={
                    "tool": name,
                    "request_id": request_id,
                    "status": "failed",
                    "failure_kind": rendering.kind,
                },
            )
            return _error_result(rendering, request_id)
        except Exception as exc:
            logger.error(
                "mcp tool=%s request_id=%s failed unexpectedly",
                name,
                request_id,
                exc_info=exc,
                extra={"tool": name, "request_id": request_id, "status": "failed_unexpectedly"},
            )
            return _error_result(unexpected_error_rendering(), request_id)

    # Registered by *calling* the SDK's decorator factories rather than with
    # decorator syntax. They are unannotated, and `mypy --strict` turns on
    # `disallow_untyped_decorators`, so the `@` form reports `untyped-decorator`
    # on *both* handlers — erasing their types — on top of the call below. The
    # `@` form costs three suppressions here and this form costs one, for the
    # same call. `unused-ignore` is paired on so a future SDK release that
    # annotates `list_tools` does not turn a stale suppression into a failure.
    server.list_tools()(_list_tools)  # type: ignore[no-untyped-call,unused-ignore]
    server.call_tool(validate_input=False)(_call_tool)
    return server


async def list_tool_definitions(ctx: ServiceContext) -> list[types.Tool]:
    """Return the tools a freshly built server actually registers.

    Drives the registered ``tools/list`` handler rather than re-deriving the
    list from :data:`TOOLS`. That distinction is the whole value of the parity
    test: re-deriving would compare the registry against itself and pass even if
    registration were broken or a tool were added directly to the server.

    Raises:
        ConfigurationError: The installed SDK did not answer ``tools/list``
            with a ``ListToolsResult``. Unreachable under the ``mcp>=1.29,<2``
            pin, which exists for exactly this dispatch contract.
    """
    server = build_mcp_server(ctx)
    result = await server.request_handlers[types.ListToolsRequest](None)
    payload = result.root
    if isinstance(payload, types.ListToolsResult):
        return list(payload.tools)
    raise ConfigurationError(
        "the installed MCP SDK answered tools/list with "
        f"{type(payload).__name__}, not ListToolsResult; its dispatch contract has changed"
    )


def create_session_manager(
    ctx: ServiceContext,
    *,
    host_allow_list: HostAllowList = LOOPBACK_HOST_ALLOW_LIST,
) -> StreamableHTTPSessionManager:
    """Build the streamable-HTTP session manager to mount at :data:`MCP_HTTP_PATH`.

    The caller owns the lifecycle and must enter ``manager.run()`` for the app's
    lifetime before routing anything to ``manager.handle_request``; the instance
    is single-use and cannot be restarted.

    Stateful with an idle timeout, rather than ``stateless=True``: sessions are
    what the standard transport negotiates, and the reason to avoid them here
    would be unbounded growth on an unauthenticated port, which
    :data:`_SESSION_IDLE_TIMEOUT_SECONDS` bounds directly. ``event_store`` is
    ``None`` because a read-only surface has nothing to replay — resumability
    exists for streams a client must not miss events from, and every response
    here is reproducible by asking again.

    **DNS-rebinding protection is on, driven by the serve-time bind decision**
    (ADR-0024). The SDK defaults ``security_settings`` to off for backwards
    compatibility, and its own convenience server (``FastMCP``) overrides that
    default for a loopback host precisely because the bind is not a boundary
    against a browser: a page can re-point its own hostname at ``127.0.0.1``,
    and every request the browser then makes is same-origin — no preflight, the
    response readable. This module uses the lower-level ``Server`` /
    ``StreamableHTTPSessionManager`` API, which bypasses that override, so the
    settings are built here from
    :class:`~groundkit.service.binding.HostAllowList` instead. Both the
    ``Host`` and the ``Origin`` list come from that one object, so this
    transport and the REST surface cannot drift into disagreeing about who may
    connect.

    This check is **not** the only one on the HTTP path: mounted under
    :func:`groundkit.service.api.create_app`, Starlette's
    ``TrustedHostMiddleware`` has already refused a forged ``Host`` before the
    request reaches here. It is duplicated deliberately, because the manager is
    a public constructor a caller may mount anywhere, and a transport whose
    protection depends on the app someone wrapped it in has no protection of
    its own. The two refusals differ in status code (Starlette answers 400, the
    SDK 421/403) and that is left alone: each matcher renders its own refusal,
    and wrapping them into one shape would mean re-implementing both.

    The default is :data:`~groundkit.service.binding.LOOPBACK_HOST_ALLOW_LIST`
    (ADR-0025), for the reason :func:`groundkit.service.api.create_app` gives
    about its own: the bind decision is made at serve time, and ``grk serve``
    always passes the derived list regardless of this default, so the two
    coincide only for the common case, a loopback bind. A caller that never
    passes ``host_allow_list`` gets the same fail-closed posture as that
    default bind rather than every ``Host`` accepted; one that needs the wider
    behavior opts in explicitly with
    :data:`~groundkit.service.binding.UNRESTRICTED_HOST_ALLOW_LIST`.

    Args:
        ctx: Serve-time context every handler is invoked with.
        host_allow_list: The ``Host``/``Origin`` decision this transport
            enforces, derived by
            :func:`groundkit.service.binding.derive_host_allow_list`.

    Returns:
        A manager wrapping a server built from the same registry as stdio's.
    """
    return StreamableHTTPSessionManager(
        app=build_mcp_server(ctx),
        event_store=None,
        json_response=False,
        stateless=False,
        session_idle_timeout=_SESSION_IDLE_TIMEOUT_SECONDS,
        security_settings=TransportSecuritySettings(
            enable_dns_rebinding_protection=host_allow_list.enforced,
            allowed_hosts=list(host_allow_list.mcp_allowed_hosts),
            allowed_origins=list(host_allow_list.mcp_allowed_origins),
        ),
    )


def _force_logging_to_stderr() -> None:
    """Re-point every stdout-bound log handler at stderr.

    ADR-0014 decision 5: on stdio, stdout carries JSON-RPC frames and nothing
    else, so one log record written there corrupts the stream for the rest of
    the session.

    Existing handlers are *re-pointed* rather than removed, so an operator's
    formatter and level survive. ``basicConfig`` cannot do this job on its own —
    it is a no-op once any handler exists, so it could never fix an already
    installed stdout handler; it only supplies a default when there is nothing
    at all.

    Every configured logger is swept, not just the root: a library or an
    operator's ``dictConfig`` may attach a stdout handler to a package logger,
    and the protocol breaks the same way from there.
    """
    loggers: list[logging.Logger] = [logging.getLogger()]
    loggers.extend(
        existing
        for existing in logging.Logger.manager.loggerDict.values()
        if isinstance(existing, logging.Logger)
    )
    for target in loggers:
        for handler in target.handlers:
            if isinstance(handler, logging.StreamHandler) and handler.stream is sys.stdout:
                handler.setStream(sys.stderr)
    if not logging.getLogger().handlers:
        logging.basicConfig(stream=sys.stderr)


async def run_stdio(ctx: ServiceContext) -> None:
    """Serve MCP over stdio until the client closes stdin.

    Logging is re-pointed **before** the server runs, because the first record
    written after the transport opens is already too late.

    Args:
        ctx: Serve-time context every handler is invoked with.
    """
    _force_logging_to_stderr()
    server = build_mcp_server(ctx)
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())
