"""Deterministic PDF/HTML extraction and the extractor registry (Wave 3).

Covers ``groundkit.extraction`` (ADR-0016 decisions 2, 3, 5;
``docs/specs/loaders-extracted-and-remote-sources.md`` §9) and the
``extracted``-class branch of ``resolve_citation`` that Wave 3 wires to it.

The determinism assertions are the point of this file, not incidental
coverage: ADR-0016 decision 2's whole mechanism assumes "same bytes in, same
text out", and the two ways that silently stops being true -- an
environment-selected HTML parser and pypdf's font-metric-dependent "layout"
mode -- produce code that looks correct and is not. §9.1 spells both out; the
tests below pin the pinned choices rather than trusting the constants to stay
put.
"""

from __future__ import annotations

import asyncio
import builtins
import importlib.metadata
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest

from groundkit import extraction
from groundkit.contracts import Citation
from groundkit.errors import ConfigurationError, IngestionError, RetrievalError
from groundkit.extraction import (
    ExtractorProtocol,
    PdfExtractor,
    active_extractors,
    html_extractor,
    pdf_extractor,
)
from groundkit.retrieval.citations import resolve_citation


@pytest.fixture(autouse=True)
def _clear_extractor_caches() -> Iterator[None]:
    """Reset every ``lru_cache`` in :mod:`groundkit.extraction` around a test.

    All three accessors are memoized per process (§9.2), so a test that
    monkeypatches availability would otherwise leak its registry into the
    next test -- and, worse, would silently inherit one built before its
    patch was applied. Cleared on both sides so ordering cannot matter.
    """
    for cached in (pdf_extractor, html_extractor, active_extractors):
        cached.cache_clear()
    yield
    for cached in (pdf_extractor, html_extractor, active_extractors):
        cached.cache_clear()


def _minimal_pdf(*pages: str) -> bytes:
    """Build a PDF with one text-drawing page per argument, with a real xref.

    Handwritten rather than produced with ``pypdf`` on purpose: a fixture
    generated by the same library under test cannot distinguish "extraction
    works" from "the round trip through one library's own assumptions
    works".
    """
    streams = [f"BT /F1 12 Tf 72 720 Td ({page}) Tj ET".encode("ascii") for page in pages]
    page_ids = [4 + 2 * i for i in range(len(streams))]

    bodies: list[bytes] = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids ["
        + b" ".join(f"{pid} 0 R".encode() for pid in page_ids)
        + b"] /Count "
        + str(len(streams)).encode()
        + b" >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    for i, stream in enumerate(streams):
        bodies.append(
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents "
            + str(page_ids[i] + 1).encode()
            + b" 0 R /Resources << /Font << /F1 3 0 R >> >> >>"
        )
        bodies.append(
            b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream"
        )

    out = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for number, body in enumerate(bodies, start=1):
        offsets.append(len(out))
        out += str(number).encode() + b" 0 obj\n" + body + b"\nendobj\n"

    xref_at = len(out)
    size = len(bodies) + 1
    out += b"xref\n0 " + str(size).encode() + b"\n0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += b"trailer\n<< /Size " + str(size).encode() + b" /Root 1 0 R >>\nstartxref\n"
    out += str(xref_at).encode() + b"\n%%EOF\n"
    return bytes(out)


def _citation(source: str, *, extractor: str, start: int = 0, end: int = 5) -> Citation:
    return Citation(
        document_id="d1",
        chunk_id="c1",
        source=source,
        start_offset=start,
        end_offset=end,
        source_class="extracted",
        extractor=extractor,
    )


# -- PdfExtractor -----------------------------------------------------------


class TestPdfExtractor:
    def test_identity_is_the_installed_distribution_and_version(self) -> None:
        """Derived from distribution metadata, never hardcoded (§9.1), so a
        library upgrade changes it without a manual version-tracking step.
        """
        assert pdf_extractor().identity == f"pypdf/{importlib.metadata.version('pypdf')}"

    def test_extracts_page_text(self, tmp_path: Path) -> None:
        pdf = tmp_path / "a.pdf"
        pdf.write_bytes(_minimal_pdf("Hello groundkit"))
        assert "Hello groundkit" in asyncio.run(pdf_extractor().extract(pdf))

    def test_pages_are_joined_with_the_pinned_separator(self, tmp_path: Path) -> None:
        """The join is part of what "the same extractor" must mean identically
        at ingest and resolve time, so it is pinned rather than incidental.
        """
        pdf = tmp_path / "two.pdf"
        pdf.write_bytes(_minimal_pdf("First page", "Second page"))
        text = asyncio.run(pdf_extractor().extract(pdf))
        assert extraction._PDF_PAGE_SEPARATOR in text
        assert text.index("First page") < text.index("Second page")

    def test_extraction_is_deterministic(self, tmp_path: Path) -> None:
        pdf = tmp_path / "a.pdf"
        pdf.write_bytes(_minimal_pdf("Repeatable output"))
        first = asyncio.run(pdf_extractor().extract(pdf))
        second = asyncio.run(pdf_extractor().extract(pdf))
        assert first == second

    def test_extraction_mode_is_pinned_to_plain(self) -> None:
        """pypdf's "layout" mode depends on system font metrics, which would
        make extraction a function of the machine rather than of the file's
        bytes (§9.1). Never left at whatever pypdf currently defaults to.
        """
        assert extraction._PDF_EXTRACTION_MODE == "plain"

    def test_a_corrupt_pdf_raises_ingestion_error(self, tmp_path: Path) -> None:
        """pypdf's own exception hierarchy must never escape this module's
        documented contract.
        """
        broken = tmp_path / "broken.pdf"
        broken.write_bytes(b"%PDF-1.4\nnot actually a pdf\n%%EOF\n")
        with pytest.raises(IngestionError, match="Failed to extract PDF text"):
            asyncio.run(pdf_extractor().extract(broken))

    def test_a_missing_file_raises_ingestion_error(self, tmp_path: Path) -> None:
        with pytest.raises(IngestionError, match="Failed to extract PDF text"):
            asyncio.run(pdf_extractor().extract(tmp_path / "absent.pdf"))


# -- HtmlExtractor ----------------------------------------------------------


class TestHtmlExtractor:
    def test_identity_uses_the_distribution_name_not_the_import_name(self) -> None:
        """``importlib.metadata.version("bs4")`` raises ``PackageNotFoundError``
        -- import name and distribution name differ for this package, and §9.1
        calls it out as an easy silent-until-runtime mistake.
        """
        expected = importlib.metadata.version("beautifulsoup4")
        assert html_extractor().identity == f"beautifulsoup4/{expected}"
        assert not html_extractor().identity.startswith("bs4/")

    def test_tags_are_stripped_and_text_kept(self, tmp_path: Path) -> None:
        page = tmp_path / "a.html"
        page.write_text("<html><body><h1>Title</h1><p>Body text</p></body></html>", "utf-8")
        text = asyncio.run(html_extractor().extract(page))
        assert "Title" in text
        assert "Body text" in text
        assert "<h1>" not in text
        assert "body" not in text.lower().replace("body text", "")

    def test_script_and_style_bodies_are_removed_not_merely_skipped(self, tmp_path: Path) -> None:
        """The hazard ``_HTML_STRIPPED_TAGS`` exists for: ``get_text()`` walks
        every ``NavigableString`` regardless of its parent tag, so a script
        body is ordinary text to it and would be indexed as prose -- BM25
        scoring JavaScript as content, one level below the "<div> as a term"
        problem ADR-0016 decision 3 exists to avoid.
        """
        page = tmp_path / "a.html"
        page.write_text(
            "<html><head><style>.x{color:red}</style>"
            "<script>var secret = 'tracker';</script></head>"
            "<body><p>Real content</p></body></html>",
            "utf-8",
        )
        text = asyncio.run(html_extractor().extract(page))
        assert "Real content" in text
        assert "tracker" not in text
        assert "color:red" not in text

    def test_the_parser_is_pinned_to_the_stdlib_one(self) -> None:
        """Omitting the parser lets bs4 auto-select the "best available" one,
        which depends on whether lxml/html5lib happen to be installed -- the
        same bytes could then parse differently in CI than on an operator's
        machine (§9.1).
        """
        assert extraction._HTML_PARSER == "html.parser"

    def test_extraction_is_deterministic(self, tmp_path: Path) -> None:
        page = tmp_path / "a.html"
        page.write_text("<p>One</p><p>Two</p>", "utf-8")
        assert asyncio.run(html_extractor().extract(page)) == asyncio.run(
            html_extractor().extract(page)
        )

    def test_non_utf8_raises_ingestion_error(self, tmp_path: Path) -> None:
        """Mirrors ``FileLoader``'s ``UnicodeDecodeError`` handling rather than
        introducing a second, environment-sensitive decoding path (§9.1).
        """
        page = tmp_path / "latin1.html"
        page.write_bytes(b"<p>caf\xe9</p>")
        with pytest.raises(IngestionError, match="not valid UTF-8"):
            asyncio.run(html_extractor().extract(page))

    def test_an_unreadable_file_raises_ingestion_error(self, tmp_path: Path) -> None:
        with pytest.raises(IngestionError, match="Failed to read"):
            asyncio.run(html_extractor().extract(tmp_path / "absent.html"))


# -- missing extras ---------------------------------------------------------


class TestMissingExtra:
    """ADR-0016 decision 5: a missing extra is a typed error naming the install."""

    @staticmethod
    def _block(monkeypatch: pytest.MonkeyPatch, blocked: str) -> None:
        real_import = builtins.__import__

        def _fake_import(name: str, *args: Any, **kwargs: Any) -> Any:
            if name == blocked:
                raise ImportError(f"No module named {name!r}")
            return real_import(name, *args, **kwargs)

        monkeypatch.setattr(builtins, "__import__", _fake_import)

    def test_missing_pypdf_names_the_pdf_extra(self, monkeypatch: pytest.MonkeyPatch) -> None:
        self._block(monkeypatch, "pypdf")
        with pytest.raises(ConfigurationError, match=r"groundkit\[pdf\]"):
            extraction._import_pypdf()

    def test_missing_bs4_names_the_html_extra(self, monkeypatch: pytest.MonkeyPatch) -> None:
        self._block(monkeypatch, "bs4")
        with pytest.raises(ConfigurationError, match=r"groundkit\[html\]"):
            extraction._import_bs4()


# -- active_extractors ------------------------------------------------------


class TestActiveExtractors:
    def test_registry_is_keyed_by_identity(self) -> None:
        registry = active_extractors()
        assert registry[pdf_extractor().identity] is pdf_extractor()
        assert registry[html_extractor().identity] is html_extractor()

    def test_both_extras_are_present_in_this_environment(self) -> None:
        """Both are pinned in the dev group, so the default suite -- not a
        separate gated one -- is the non-``continue-on-error`` proof of each
        backend that SPEC.md §3 requires. If this fails, that wiring broke.
        """
        assert len(active_extractors()) == 2

    def test_the_registry_is_memoized(self) -> None:
        assert active_extractors() is active_extractors()

    def test_one_missing_extra_does_not_blank_the_other(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Each candidate is probed independently: a build with only ``html``
        installed must still resolve HTML citations.
        """

        def _unavailable() -> PdfExtractor:
            raise ConfigurationError("pdf extra absent")

        monkeypatch.setattr(extraction, "_EXTRACTOR_ACCESSORS", (_unavailable, html_extractor))
        active_extractors.cache_clear()
        registry = active_extractors()
        assert list(registry) == [html_extractor().identity]

    def test_a_non_configuration_error_is_not_swallowed(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Only ``ConfigurationError`` is caught (never a broader except): a
        genuine bug inside an installed extractor's construction must not be
        silently reported as "not registered".
        """

        def _broken() -> PdfExtractor:
            raise RuntimeError("bug inside extractor construction")

        monkeypatch.setattr(extraction, "_EXTRACTOR_ACCESSORS", (_broken,))
        active_extractors.cache_clear()
        with pytest.raises(RuntimeError, match="bug inside extractor construction"):
            active_extractors()

    def test_an_empty_registry_is_a_valid_state(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """A base install with neither extra: every ``extracted`` citation
        refuses, which is correct rather than degraded.
        """
        monkeypatch.setattr(extraction, "_EXTRACTOR_ACCESSORS", ())
        active_extractors.cache_clear()
        assert active_extractors() == {}

    def test_both_implementations_satisfy_the_protocol(self) -> None:
        assert isinstance(pdf_extractor(), ExtractorProtocol)
        assert isinstance(html_extractor(), ExtractorProtocol)


# -- resolve_citation, extracted class --------------------------------------


class TestResolveExtractedCitation:
    def test_a_matching_identity_re_extracts_and_slices(self, tmp_path: Path) -> None:
        """The Wave 3 behaviour change: re-extract, slice, compare (ADR-0016
        decision 1's table). Before this wave every ``extracted`` citation
        refused, because the active set could never be populated.
        """
        page = tmp_path / "a.html"
        page.write_text("<p>Hello</p>", "utf-8")
        extracted = asyncio.run(html_extractor().extract(page))
        assert extracted.startswith("Hello")

        resolved = asyncio.run(
            resolve_citation(
                _citation(str(page), extractor=html_extractor().identity, start=0, end=5),
                tmp_path,
            )
        )
        assert resolved == "Hello"

    def test_an_unknown_identity_is_unresolvable(self, tmp_path: Path) -> None:
        page = tmp_path / "a.html"
        page.write_text("<p>Hello</p>", "utf-8")
        with pytest.raises(RetrievalError) as exc_info:
            asyncio.run(
                resolve_citation(_citation(str(page), extractor="beautifulsoup4/0.0.0"), tmp_path)
            )
        assert exc_info.value.verdict == "unresolvable"
        assert "beautifulsoup4/0.0.0" in str(exc_info.value)

    def test_a_re_extraction_failure_is_unresolvable_not_drifted(self, tmp_path: Path) -> None:
        """A parse failure means the check never got far enough to compare
        anything, which is what ``unresolvable`` means -- ``drifted`` is
        reserved for text that was obtained and disagrees (ADR-0016 decision
        6). No fourth verdict is introduced.
        """
        broken = tmp_path / "broken.pdf"
        broken.write_bytes(b"%PDF-1.4\nnot actually a pdf\n%%EOF\n")
        with pytest.raises(RetrievalError) as exc_info:
            asyncio.run(
                resolve_citation(
                    _citation(str(broken), extractor=pdf_extractor().identity), tmp_path
                )
            )
        assert exc_info.value.verdict == "unresolvable"
        assert "re-extraction with" in str(exc_info.value)

    def test_offsets_past_the_extracted_length_are_drifted(self, tmp_path: Path) -> None:
        """The shared offset check applies to extracted text exactly as it does
        to a raw read -- once text exists, how it was produced stops mattering.
        """
        page = tmp_path / "a.html"
        page.write_text("<p>Hi</p>", "utf-8")
        with pytest.raises(RetrievalError) as exc_info:
            asyncio.run(
                resolve_citation(
                    _citation(str(page), extractor=html_extractor().identity, start=0, end=9_999),
                    tmp_path,
                )
            )
        assert exc_info.value.verdict == "drifted"

    def test_containment_is_checked_before_the_extractor_lookup(self, tmp_path: Path) -> None:
        """Wave 3 moved the containment check ahead of the extractor branch
        (§9.3), so an escaping source is refused as a path violation rather
        than reported as an extractor-identity problem. Containment is the
        security boundary; it answers first.
        """
        outside = tmp_path.parent / "outside.html"
        with pytest.raises(RetrievalError) as exc_info:
            asyncio.run(
                resolve_citation(_citation(str(outside), extractor="whatever/1"), tmp_path / "base")
            )
        assert exc_info.value.verdict == "unresolvable"
        assert "extractor identity recorded at ingest" not in str(exc_info.value)
